-- SAMPLE DATA for the demo only. Prices, dates and descriptions are placeholders –
-- delete these and add the real stock through /admin.
DELETE FROM clocks;
INSERT INTO clocks (title, type, maker, origin, period, year, price, description, dimensions, images, status, featured) VALUES
('Eight-Day Painted Dial Longcase Clock', 'Longcase', 'John Matthew', 'English', 'c. 1790', 1790, 4850,
 'A handsome eight-day longcase clock with a finely painted arched dial depicting a rural scene, striking the hours on a bell. Housed in a well-figured oak case with mahogany crossbanding, swan-neck pediment and brass finials. Fully overhauled in our workshop.',
 'Height 218 cm', '["/img/clocks/longcase.svg"]', 'available', 1),
('Double Fusee Bracket Clock', 'Bracket', NULL, 'English', 'c. 1840', 1840, 3200,
 'A William IV double fusee bracket clock in a rosewood case with brass inlay and pineapple finials. The silvered dial with Roman numerals; the twin fusee movement strikes the hours on a bell. Overhauled and guaranteed.',
 'Height 48 cm', '["/img/clocks/bracket.svg"]', 'available', 1),
('French Four Glass Mantel Clock', 'Four Glass', NULL, 'French', 'c. 1880', 1880, 1650,
 'An elegant French four glass clock in a polished brass case with bevelled glass panels and a visible Brocot escapement. The eight-day movement strikes the hours and half hours on a gong, with mercury compensated pendulum.',
 'Height 36 cm', '["/img/clocks/fourglass.svg"]', 'available', 1),
('Brass Skeleton Clock under Glass Dome', 'Skeleton', NULL, 'English', 'c. 1860', 1860, 2750,
 'A quality Victorian single fusee skeleton clock with pierced brass frame, chapter ring dial and passing strike on a bell. Raised on a marble base and complete with its original glass dome.',
 'Height 46 cm (with dome)', '["/img/clocks/skeleton.svg"]', 'available', 0),
('Thomas Cole Mantel Clock', 'Mantel', 'Thomas Cole', 'English', 'c. 1850', 1850, NULL,
 'A rare gilt-brass mantel clock by the celebrated Victorian maker Thomas Cole, with engraved case and silvered dial. A fine example of his work. Please contact us for further details and price.',
 'Height 30 cm', '["/img/clocks/mantel.svg"]', 'available', 0),
('Ship''s Chronometer in Brass-Bound Box', 'Chronometer', NULL, 'English', 'c. 1870', 1870, 5400,
 'A two-day marine chronometer with silvered dial, subsidiary seconds and up/down indicator, gimbal-mounted in a three-tier brass-bound mahogany box. Serviced and running to time.',
 'Box 19 cm square', '["/img/clocks/chronometer.svg"]', 'available', 0),
('Victorian Fusee Dial Wall Clock', 'Wall', NULL, 'English', 'c. 1870', 1870, 895,
 'A classic 12-inch mahogany fusee dial clock, ideal for a hallway or kitchen. Painted dial with Roman numerals and an eight-day single fusee movement. Fully serviced.',
 'Diameter 36 cm', '["/img/clocks/wall.svg"]', 'available', 0),
('French Carriage Clock with Repeat', 'Carriage', NULL, 'French', 'c. 1890', 1890, 1150,
 'A gilt-brass corniche-cased carriage clock with enamel dial, striking the hours and half hours on a gong with push repeat. Complete with its original leather travelling case.',
 'Height 15 cm (handle down)', '["/img/clocks/carriage.svg"]', 'reserved', 0),
('Thirty-Hour Oak Longcase Clock', 'Longcase', NULL, 'English', 'c. 1770', 1770, 2400,
 'A country oak thirty-hour longcase clock with a square brass dial and single-hand-style chapter ring, striking on a bell. A charming and honest example in a plain oak case.',
 'Height 200 cm', '["/img/clocks/longcase.svg"]', 'available', 0),
('Black Slate Mantel Clock', 'Mantel', NULL, 'French', 'c. 1885', 1885, 495,
 'A French black slate and marble mantel clock in the architectural style, with eight-day movement striking on a bell. Good honest example, serviced.',
 'Height 32 cm', '["/img/clocks/mantel.svg"]', 'sold', 0);
